# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.IntegerField(blank=True),
        ),
    ]
