# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20161001_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.IntegerField(default=1),
        ),
    ]
