# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20161001_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ask',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='bid',
            field=models.FloatField(),
        ),
    ]
